### ISSUE TITLE
access-token always refresh regardless `autoRefreshToken` setting when token expired

### ISSUE THREAD

**Issue by michael-land** [supabase/gotrue-js#677] opened 2023-05-11 06:46 UTC
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

when token is expired and `autoRefreshToken` set to false, it first remove the session in `_recoverAndRefresh`, then it will `_callRefreshToken` in `getSession`. which implicit refresh the access-token.

https://github.com/supabase/gotrue-js/blob/master/src/GoTrueClient.ts#L714-L721

## To Reproduce
1. set jwt_expiry to 10
2. wait jwt expire
3. invoke `getSession`

## Expected behavior

respect autoRefreshToken

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by j4w8n** [comment] 2023-05-11 18:33
`autoRefreshToken` is behaving as intended here.

However, to your point, the token will get refreshed if it's expired, whenever you call `getSession` or `setSession`.

I do see where the `_recoverAndRefresh` function checks the value of `autoRefreshToken` before it refreshes the session. Maintainers would need to do some research on whether that check should be added to `getSession` and `setSession`. It's likely a breaking change.

How is the current behavior affecting your app?

**Comment by michael-land** [comment] 2023-05-11 19:28
> How is the current behavior affecting your app?

If a user accesses my app and their token is due to expire in 10 seconds, Supabase will automatically log them out.

i'm using nextjs auth-helpers, invoke supabse.auth.getSession in middleware

**Comment by kangmingtay** [comment] 2023-05-22 11:27
Hi @michael-land, it would be great if you can explain how you intend to handle the refresh on your own. Do you plan to use the `supabase.auth.refreshSession()` method? Is there a reason why you wouldn't want `getSession()` to perform the refresh on your behalf and always return a valid session? 

We implemented `getSession` to either always return a valid session or no session and i don't think we plan to change this behaviour.

**Comment by michael-land** [comment] 2023-05-22 14:45
@kangmingtay 

> Do you plan to use the supabase.auth.refreshSession() method?
yes

> Is there a reason why you wouldn't want getSession() to perform the refresh on your behalf and always return a valid session?

The reason i need to refresh token manually is that my app need to create an organization during onboarding step, and assign user an organization id in `app_meta_data` (by refresh access token) without asking user sign in again.

I think this bug exist regardless manually refresh token via `supabase.auth.refreshSession()` or delegate to supabase client handle it.

**Comment by michael-land** [comment] 2023-05-22 14:48
Based on the merge of pull request #598, I believe this bug should have already been resolved.

**Comment by kangmingtay** [comment] 2023-05-23 07:13
@michael-land we'll be closing this PR but feel free to reopen it if you're still experiencing the issue

**Closed by kangmingtay** 2023-05-23 07:13 UTC
Labels: bug
