### ISSUE TITLE
setting current session after successful third party login

### ISSUE THREAD

**Issue by awalias** [supabase/gotrue-js#2] opened 2020-09-21 14:58 UTC
after a successful third party authentication the user will be redirected to:

~~`<your-site-url>/#access_token=xyzabc&expires_in=3600&refresh_token=abcdef&token_type=bearer`~~
`<your-site-url>/?access_token=xyzabc&expires_in=3600&refresh_token=abcdef&token_type=bearer`

we need a mechanism (if supabase-js) is present on the page -> to check the page url on startup and if these values are present - to use them to set the current session

~~I find the `#` slightly strange, if it's better I can also alter gotrue to use a `?` instead so it's more like parsing query params~~

**Comment by kiwicopple** [comment] 2020-09-22 00:10
I think a `?` would definitely be easier because then I can just parse them as query params. I wonder why they made it with a `#`? That's a page anchor, but I can't think of a good justification

**Comment by awalias** [comment] 2020-09-22 02:53
Ok I will update this today to a `?`

**Comment by awalias** [comment] 2020-09-22 05:03
as of KPS v2.3.2 included here in infrastructure: https://github.com/supabase/infrastructure/commit/367758cc97a71eabc208b4a319234dd443882f26 the url is now:

`<your-site-url>/?access_token=xyzabc&expires_in=3600&refresh_token=abcdef&token_type=bearer`

**Comment by kiwicopple** [comment] 2020-09-25 07:37
Closing - this is implemented in the new gotrue-js, although I dont think we needed the `?` in the end - looks like the `#` might work better with React, although it's hard to say. I get an occasional 400 error on the `/example`, which I *think* is caused by the react dev build not dealing with the `?` (not compiling properly). 

Will revisit this if we see a problem later

**Closed by kiwicopple** 2020-09-25 07:37 UTC
Labels: enhancement, help wanted
