### ISSUE TITLE
auth.signup not return error on duplicate email 

### ISSUE THREAD

**Issue by sunstan** [supabase/gotrue-js#513] opened 2021-11-06 11:39 UTC
# Bug report
auth.signup not return error on duplicate email but return user object.

## Describe the bug
Hello everyone.
A week ago, all was ok but today, if i try to sign up with an email already registred, i have no error.
Instead, I receive an user object as if I had created my account (It does not edit account already registred).
I tryed to sign up with differents passwords, clear cache, different browser, restart server and i have the same result.
(auth.sign works. I receive user and session with valid credentials and i receive error with invalid)
.
**Anyone knows the solution?**

```
 try {
      await supabase.auth.signOut();
      const {user, session, error} = await supabase.auth.signUp({email, password});
      console.log(user, session, error); // return object, null, null
} catch (e) {
      console.log(e)
}
```

## Expected behavior

A week ago, I had an error message thanking me for signing up etc. 

## System information

- OS: Windows 10
- Browser: Tested on Chrome, Firefox, Edge
- Version of supabase-js: 1.25.2
- Version of Node.js: 14.16.0

**Comment by malewis5** [comment] 2022-11-18 04:32
Is there any update on this?

**Comment by J0** [comment] 2022-11-29 15:33
Hey team,

There are no changes for now as this is the expected behaviour we wish to maintain for now. We're adding documentation for this though.

**Comment by hf** [comment] 2022-12-30 16:58
Closing the issue until we figure out a comprehensive solution to this type of obfuscation messages.

**Closed by hf** 2022-12-30 16:58 UTC
Labels: bug, documentation, auth

**Comment by wyattharrell** [comment] 2023-05-16 14:30
> If signUp() is called for an existing confirmed user:
> If Confirm email is enabled in [your project](https://app.supabase.com/project/_/auth/providers), an obfuscated/fake user object is returned.
> If Confirm email is disabled, the error message, User already registered is returned.

I see that this was added to the documentation, but this is still an issue and confirm email is not worth using because of it. Is there a timeline on when this might be fixed?

Thanks

**Comment by wyattharrell** [comment] 2023-05-16 17:45
Or is there a way to determine that the returned user is an obfuscated/fake user object for the time being? I see both objects returned with different User UUID's.

**Comment by lovenangelo** [comment] 2023-06-06 02:18
I experience the same issue, is there a recommended way to implement this validation?

**Comment by mirsahib** [comment] 2023-07-04 13:49
this is embarrassing its been nearly two years and this issue hasn't been addressed yet

**Comment by didate** [comment] 2023-08-23 14:56
any update ?

**Comment by hf** [comment] 2023-08-24 14:24
Over time the team has considered both aspects of this, and we'll be providing a toggle for it. Different types of users of Supabase Auth exist -- ones that like the privacy offered and other's that don't. We plan on making this customizable, but I can't promise any timelines right now. Will post an update here or in general Supabase announcements channels when this arrives.

**Comment by phreakyphoenix** [comment] 2023-09-02 19:19
One compromise could be creating an editable template, and a trigger within supabase, when auth-event, "action": "user_repeated_signup" happens to send an email to the id with something like

> Hey User, Welcome back to Supabase, you just tried signing up, but you already have an account with us.
> With security and customer privacy at heart, we don't show an error message when a duplicate signup attempt is made but have not made any changes to your account and your old password will continue to work. 
> In case you'd like to reset it, you can do that from the forgot password option on your account or this link here.

Currently, we've to resort to convoluted hacks for a relatively simple objective of letting the user know if their action succeeded or not, we can't keep them in a limbo.

Is this already possible via Supabase mail templates without an external integration

**Comment by tbenci** [comment] 2023-09-25 11:21
Is there an ETA for this please. Coming across from Firebase Auth I spent half an hour questioning my code before I discovered this was a Supabase thing.

It's hard to imagine a rationale where letting a user know that the email account is already registered is NOT a thing. For what it's worth, I have email confirmation on and if I add the same user details and save it the action is successful (and I toast the success message) but NO confirmation email arrives.

This is almost a "not using it until this is fixed" issue and that would be a crying shame as we want to commit to Supabase completely. 

What other "gotchas" am I going to find?

Cheers

**Comment by pedrofrxncx** [comment] 2023-10-10 18:18
it's really hard to believe supabase team didn't manage a way to address the situation after almost two years. really, what the duck?

**Comment by pedrofrxncx** [comment] 2023-10-10 18:21
guess i'll have to make an API call to my back-end before signup to check if the email is already registered. thanks supabase team :D

**Comment by Jonny1987** [comment] 2023-10-26 12:42
Why can't we allow Confirm Email AND be told when the user already exists? I imagine these are both the most preferred options. I don't understand the rationale behind not informing that the user already exists just because Confirm Email is false

**Comment by Jonny1987** [comment] 2023-10-26 13:40
From looking at the returned User object, it looks like we see if the returned user is a dummy user (which indicates the email already exists) by seeing if User.identities is empty. Supabase, can you confirm if this strategy works please?

**Comment by yocoso** [comment] 2023-10-27 05:14
Run into the same issue and it is weird. My setting is need to confirm the email address.
At the beginning, it shows the error for  duplicated email and I just kept trying the registration, then to some point, it starts to go thru the registration with the same email and the error never show again. This bug looks intermittently now.

**Comment by utku-kaan** [comment] 2023-11-25 06:47
> From looking at the returned User object, it looks like we see if the returned user is a dummy user (which indicates the email already exists) by seeing if User.identities is empty. Supabase, can you confirm if this strategy works please?

currently building my app by assuming this is true. would love to get some confirmation on that as I'd hate to see some edge cases later down the road.

**Comment by wyattharrell** [comment] 2024-01-04 20:51
I am going to venture to say that since this bug hasn't been re-opened -  they don't care and aren't going to fix the problem.

**Comment by pat-mw** [comment] 2024-02-19 22:58
Just coming across this issue now. Need it asap. @utku-kaan any word on if your workaround is valid?

**Comment by Jonny1987** [comment] 2024-02-20 03:00
@pat-mw So I've tested this method a lot and it seems to work.
When the confirm email functionality is turned off though, an error is thrown though, with the error message "User already registered". (I have a condition checking for the actual message since it seems that supabase gives the same status code for different errors so I can't check for this)

My code is below:
`     var res = await authRepository.signUp(email, password, username);
      final bool userAlreadyExists = res.user!.identities!.isEmpty;
      final bool confirmationSent = res.user!.confirmationSentAt != null

      if (userAlreadyExists) {
        // set state to userExistsState
      } else if (confirmationSent) {
        // set state to confirmationSentState
      } else {
        // set state to registeredState
      }
    } on AuthException catch (e, st) {
      if (e.message == "User already registered") {
        // set state to userExistsState
      } else {
        // set state to unexpectedErrorState
    } catch (e, st) {
      // set state to unexpectedErrorState
    }`

**Comment by Jonny1987** [comment] 2024-02-20 03:04
@pat-mw So I've tested this method a lot and it seems to work.
When the confirm email functionality is turned off though, an error is thrown though, with the error message "User already registered". (I have a condition checking for the actual message since it seems that supabase gives the same status code for different errors so I can't check for this)

My code is below:
`    try {
      var res = await authRepository.signUp(email, password, username);
      final bool userAlreadyExists = res.user!.identities!.isEmpty;
      final bool confirmationSent = res.user!.confirmationSentAt != null
      if (userAlreadyExists) {
        // set state to userExistsState
      } else if (confirmationSent) {
        // set state to confirmationSentState
      } else {
        // set state to registeredState
      }
    } on AuthException catch (e, st) {
      if (e.message == "User already registered") {
        // set state to userExistsState
      } else {
        // set state to unexpectedErrorState
    } catch (e, st) {
      // set state to unexpectedErrorState
    }`

**Comment by irfanonk** [comment] 2024-03-07 14:42
this issue does not occur in local so hard to catch .
Thanks to @Jonny1987 we have implemented same solution since identities returns an empty array for duplicate email

**Comment by eluchsinger** [comment] 2024-04-20 17:58
I welcome a security-first approach, but the execution is lacking a bit here.

1. I'm pretty new to NextJS, but shouldn't this be server-side? And we trust server-side. There's no need to hide duplicate users for security reasons from the trusted backend?
2. The "fake" user returned currently has the UserID of the real user, and while some fields are fake (like the create date is recent), other fields are real, like the user id. If we're talking about a security feature for me this is at least as bad as what we're trying to avoid in the first place.
3. The most important point of all: The documentation lacks. The current documentation only says "A fake user will be returned". This is not enough. I would expect information about how to distinguish fake from not fake at least and possibly alternatives.
4. By avoiding this "loophole", we are driving users to open up other parts of the system. For example, I run logic after signing up a user, generating entries in 3rd party services. This logic is now able to run multiple times and creates a multitude of follow-up-issues: data integrity, possibility of DDoS, etc.


For me, the identity array is filled up after duplicating users. I'm not sure - I thought first I saw it empty (I even have a screenshot), but now it's returning it consistently and I'm unsure why.

**Comment by MJUrian-Learner** [comment] 2024-08-06 09:45
Using a helper function that utilize service role key can be good to check if user exist

**Comment by chandlerimhof** [comment] 2025-05-01 04:50
Supabase guidance on this is either really buried in the docs or after almost four years - their team still hasn't gotten around to adding notes clarifying the security 'feature' that returns a fake user. I happened to stumble across this thread searching on this very issue. 

Supabase team should really consider adding a toggle/dropdown in the UI (in the Auth > User Signups section) that allows us to select whether we want a fake user returned or an error thrown on duplicate email registrations. This certainly would resolve the confusion moving forward.

**Comment by itsantonle** [comment] 2025-05-02 21:04
Stumbled upon this thread, wondering why supabase was not throwing errors and checked the logs. It does not send a confirmation to my test email too so until I checked the logs and did some searching, i was in the dark. hope that supabase adds an option to send back errors or not (acknowledging user privacy)

**Comment by angus-cx** [comment] 2025-05-09 05:29
In my opinion, returning a fake user is meaningless. As long as Enable Captcha protection is turned on for login and registration, attackers can be prevented from user enumeration and brute-force attacks. There is no risk at all.

**Comment by vexkiddy** [comment] 2025-08-16 23:15
Hiya @kiwicopple, any idea if some of the above solutions to this problem might be used ? It sounds like there is a secure server side way of doing no ? Looks like many others, including me, would really love to see a secure path forward, as showing if an account exists really makes the UX much better. Surely allowing admins a way to enable and disable this at their discretion could be a path forward ?
