### ISSUE TITLE
Clarify usage of setSession() in v2.0.0

### ISSUE THREAD

**Issue by j4w8n** [supabase/gotrue-js#490] opened 2022-10-14 22:13 UTC
# Bug report

## Describe the bug

There are a couple of things going on here. One is documentation, the other is a possible bug.

1. Documentation seems to imply you have to pass an `access_token`, `refresh_token`, and a `user`. But I'm able to make this work without passing in a `user`.
```
* @param currentSession The current session that minimally contains an access token, refresh token and a user.
```
2. Based on things I've seen, it seems like the maintainers only want tokens being refreshed if the current `access_token` has expired (or possibly within the `EXPIRY_MARGIN` too, per a [pull comment](https://github.com/supabase/gotrue-js/pull/482#issuecomment-1279362251)). With current code, you can bypass `hasExpired`, and get new tokens, by passing in an empty string for the `access_token` - even if the current `access_token` is still valid.
```
const { data, error } = await supabaseClient.auth.setSession({ access_token: "", refresh_token })
```
I like being able to do this, so that I can get new tokens before the current one has expired. However, as long as there's no downside to user experience, then I'm good with only refreshing if expired. Maybe need to do a check for `access_token`, otherwise throw the `AuthSessionMissingError`.

## Expected behavior

I'm unsure of the expected behavior, but assume we shouldn't be allowed to pass in an empty string for the `access_token`.

## System information

- OS: [macOS]
- Browser (if applies) [Firefox]
- Version of supabase-js: [2.0.0]
- Version of Node.js: [16.15.0]

**Comment by hf** [comment] 2022-10-16 09:39
Hey @j4w8n great feedback!

> I like being able to do this, so that I can get new tokens before the current one has expired. However, as long as there's no downside to user experience, then I'm good with only refreshing if expired. Maybe need to do a check for access_token, otherwise throw the AuthSessionMissingError.

This is something we don't have an API for today, but should have it. I'm adding this to our internal backlog, and it's going to take a while before we get around to it. I'm encouraging you or the community to submit a PR if you can / want to.

> I'm unsure of the expected behavior, but assume we shouldn't be allowed to pass in an empty string for the access_token.

Yeah, passing an empty string for `access_token` is not what was intended with the API.

**Comment by j4w8n** [comment] 2022-10-16 12:14
Roger that, thanks! I'll write something up.

**Comment by hf** [comment] 2022-11-09 15:29
Closing this. Reopen if you think this needs more attention.

**Closed by hf** 2022-11-09 15:29 UTC
Labels: bug, good first issue, hacktoberfest
