### ISSUE TITLE
redirectTo missing in magic link

### ISSUE THREAD

**Issue by leadream** [supabase/gotrue-js#310] opened 2022-07-08 01:47 UTC
# Bug report

## Describe the bug
In my code, I set `redirectTo` in the options.

```js
let { user, error } = await supabase.auth.signIn({
  email: values.email
}, {
  redirectTo: backUrl ? backUrl : encodeURIComponent('/dashboard')
})
```

After logging in, I didn't find `redirectTo` in the URL. The URL is:

```
http://localhost:3000/logged-in#access_token=ACCESS_TOKEN&expires_in=604800&refresh_token=REFRESH_TOKEN&token_type=bearer&type=magiclink
```

## Additional context

The function I want to achieve is like:
- User clicks a link `https://abc.com/dashboard`
- This page is only accessible to logged users, so this user is redirected to `https://abc.com/login?backUrl=/dashboard`
- User login by the magic link
- Click the magic link in the email, this user is navigated to `https://abc.com/logged-in#access_token=fg47hjtyui…?redirect_to=/dashboard`
- This user logged in and redirect to `/dashboard`

**Comment by kangmingtay** [comment] 2022-07-19 03:46
hey @leadream, the `redirect_to` field is found in the query param of the magic link sent to your email. When you click on the link, supabase auth redirects you based on the `redirect_to` in that link. 

The URL you have pasted above is the end result of a successful verification and redirect. It seems like in this case, you were redirected to `http://localhost:3000/logged-in` 

Gonna close this issue since this is not a bug and is expected behaviour.

**Closed by kangmingtay** 2022-07-19 03:46 UTC
Labels: bug

**Comment by leadream** [comment] 2022-07-19 04:54
@kangmingtay  I've checked the link in email. It's like below:
```
https://SUPABASE_PROJECT_KEY.supabase.co/auth/v1/verify?token=TOKEN&type=magiclink&redirect_to=http://localhost:3000/logged-in
```
The `redirect_to` is what I set in email template, not the parameter passed in `supabase.auth.signIn`.

If this `redirect_to` is not for my need then how can I achieve it?

**Comment by kangmingtay** [comment] 2022-07-19 05:10
@leadream you'll need to whitelist the URL you want to use in the `supabase.auth.signIn` function under the "Redirect URLs" in the auth settings page in the dashboard.

<img width="1772" alt="image" src="https://user-images.githubusercontent.com/28647601/179669537-affe0370-8ffb-4e6c-975d-438e0b16d197.png">

**Comment by leadream** [comment] 2022-07-19 06:09
@kangmingtay Thanks, I'll try it.
