### ISSUE TITLE
Third party sign-in returns null values

### ISSUE THREAD

**Issue by Adoobdoob71** [supabase/gotrue-js#401] opened 2021-09-11 19:08 UTC
# Bug report

## Describe the bug

When I tried getting the values after third party sign-in with github, for some reason I get null values

## To Reproduce

`const { user, session, error } = await supabase.auth.signIn({
provider: "github"
});`
`console.log(user);`
`console.log(session);`

Both "user" and "session" are null.

## Expected behavior

These variables should contain user data

## System information

- OS: Windows
- Browser: Chrome
- Version of supabase-js: 1.22.1
- Version of Node.js: 12.13.0

[I'm not the only one experiencing this issue](https://stackoverflow.com/questions/68332321/supabase-third-party-oauth-providers-are-returning-null)

**Comment by kangmingtay** [comment] 2022-09-28 07:54
Hi @Adoobdoob71, for third-party oauth sign-in, we only create the user if the callback returned from the third-party provider is successful. When you call the `signIn` method above, all it does is to redirect the user to the corresponding third-party platform to get them to authorize the sign-in. 

We will be closing this issue since this is expected behaviour.

**Closed by kangmingtay** 2022-09-28 07:54 UTC
Labels: bug
