### ISSUE TITLE
Session removed when calling signInWithOtp

### ISSUE THREAD

**Issue by hrestrepop** [supabase/gotrue-js#621] opened 2023-02-15 00:18 UTC
# Bug report

## Describe the bug

Session is removed upon calling `signInWithOtp`.

## Expected behavior

User session should remain valid as this is just a call to sign in a user via OTP.

## Screenshots

https://user-images.githubusercontent.com/5667828/218892527-7e772880-16fb-411a-b81b-64e63f07319d.mov

## System information

- OS: MacOS
- Browser: Chrome
- Version of supabase-js: 2.7.0
- Version of Node.js: v16.14.2

## Additional context

Check out the video and see how the auth token is removed from storage after a call to `signInWithOtp` is performed.

**Comment by hrestrepop** [comment] 2023-03-07 00:28
> Hey @hrestrepop, this is expected behaviour. When calling any of the sign-in methods, we need to remove any existing sessions first before signing in the user. There should be a user session before the sign-in process is completed.
> 
> Let me know if this helps or if I'm misunderstanding something here. Thanks!

It's probably me who is misunderstanding something. All I'm trying to do is to implement an "invite users" flow through magic links, but I can't really find anything clear about that in the docs.

Any suggestions on that? Cause this method works for that, but my session gets removed even if I'm sending the invite to a user at another machine.

**Comment by kangmingtay** [comment] 2023-03-09 04:20
Hey @hrestrepop, can you elaborate abit more on the "invite users" flow? If you are trying to invite users as an admin, you can always use the [`supabase.auth.inviteUserByEmail`](https://supabase.com/docs/reference/javascript/auth-admin-inviteuserbyemail) method. 

If you plan to let your users invite other users, this is unsupported via Supabase Auth since it's a highly custom behaviour depending on the app you're trying to create. For example, in Supabase, we have an invite system to allow organization owners to invite another user to the organization. We can't use magiclinks to do this because once a user is invited to one organization, they can't be invited to another organization (since they'll already have an account with Supabase). So we handled this by creating our own invite links and sending them out on our own. 

If you're building a social media app where you want to allow a user to invite others, then maybe you can consider using magiclinks on the server-side instead. You would have to expose an endpoint on your server (`/invite` or something) which calls `signInWithOtp` under the hood. It has to be on the server-side since doing it on the client-side will logout the existing user.

However, I would highly recommend not using magiclinks for this purpose since this is not how it was intended to be used.

**Comment by hrestrepop** [comment] 2023-03-10 01:19
The product I'm working on is a multi-tenant platform. A user who signups is usually an sysadmin inside the platform —being an a sysadmin allows to create organizations (tenants), and add members to each organizations. 

So far, the only one way members of an organizations can join is by being invited by the sysadmin. Once they confirm the invitation, they are onboarded under the org and then forced to create a password.

There may be misconceptions here, I'm honestly not an expert on multi tenancy, but that's overall what I'm trying to achieve. 

Lmk if you have any suggestions, otherwise feel free guys to close the issue so you won't be bugged with this.

**Comment by kangmingtay** [comment] 2023-03-10 01:37
> So far, the only one way members of an organizations can join is by being invited by the sysadmin. Once they confirm the invitation, they are onboarded under the org and then forced to create a password.

Seems like user can potentially be invited to multiple organizations by the same sysadmin. In that case, then it's unsupported by Supabase auth and you'll need to handle the invite flow on your own.

You might want to ask the community on discord or github discussions for suggestions on how to implement the invite flow for your use case. Since this is out of the scope for this issue, i will be closing it for now but feel free to reopen it

**Closed by kangmingtay** 2023-03-10 01:37 UTC
Labels: bug
