### ISSUE TITLE
Token refresh not working

### ISSUE THREAD

**Issue by guido4000** [supabase/gotrue-js#54] opened 2021-02-07 14:33 UTC
When using the following app templates with SWR to fetch data on an interval the token refresh does not work. After one hour I get 401 Unauthorized responses from the API route. Only after reloading the app the token gets refreshed.

https://github.com/supabase/gotrue-js/tree/master/example/next
https://github.com/supabase/gotrue-js/blob/master/example/next/pages/index.js

https://github.com/supabase/supabase/tree/master/examples/nextjs-with-supabase-auth

**Comment by kiwicopple** [comment] 2021-02-08 01:43
Hi @guido4000 - I think this is a dupe of https://github.com/supabase/gotrue-js/issues/32#issuecomment-761416934

If not, feel free to reopen 👍

**Closed by kiwicopple** 2021-02-08 01:43 UTC
Labels: bug

**Comment by guido4000** [comment] 2021-02-23 12:14
@kiwicopple I am not so sure that this is a dupe. In the other ticket a domain issue is mentioned. My problem is not related to the use of multiple domains. 

Besides that I wonder if you plan to fix the token refresh issues as this should be a prerequisite for any production use of Supabase auth.

**Comment by kiwicopple** [comment] 2021-02-23 12:47
I'll drop a comment in the other issue to investigate this one simultaneously. I suspect the root-cause is the same. If it is different, I'll reopen this issue.
