### ISSUE TITLE
autoRefreshToken on does supabase client does not work

### ISSUE THREAD

**Issue by uze** [supabase/gotrue-js#563] opened 2022-12-10 20:48 UTC
# Bug report

autoRefreshToken does not refresh users access_token / JWT when it expires.

```
const createSupabaseClient = () =>
  createClient(supabaseUrl, supabaseAnonKey, {
    auth: {
      autoRefreshToken: true,
    },
  });
  ```

## Describe the bug

I'm currently working on a react native application and I sometimes keep it open for long period on one screen, but whenever I click to a new screen and a request is made to supabase I get a 401 from the request along with "JWT Expired" message. How should I properly handle the JWT for long app sessions where people typically dont log in / out all the time.

## To Reproduce

1. Set JWT expiry limit to 60s.

2. Start user session and make a supabase call where the users access_token is needed. For example:
```
      const user = await supabase.auth.getUser(access_token);
```
3. Wait 60s and make that call again. You will get this error:

```
error: AuthApiError: invalid JWT: unable to parse or verify signature, token is expired by TIME
```

## Expected behavior

When making another call the autoRefreshToken should automatically refresh the token if it is invalid.

## System information

- OS: [macOS]
- Version of supabase-js: [v2.1.0]
- Version of Node.js: [v16.13.0]
- Version of React Native : [v0.70.5]

## Additional context

Related issue:

- https://github.com/supabase/supabase/discussions/889
- https://github.com/supabase/supabase/discussions/4898
- https://github.com/supabase/gotrue-js/issues/32

**Comment by hf** [comment] 2022-12-30 14:20
@uze Can you send us a log / trace of the `ReferenceError` you mention?

**Comment by hf** [comment] 2023-03-01 14:46
Duplicate of #620

**Closed** 2023-03-01 14:46 UTC
Labels: bug

**Comment by julian-hecker** [comment] 2023-10-21 02:59
I am also having the issue with AsyncStorage. I can create a supabase client in expo just fine, but sessions aren't stored. As soon as I add `storage: AsyncStorage`, running the project gives `ReferenceError: window is not defined`.

**Comment by dongnez** [comment] 2023-11-02 19:27
This issue still valid for me:
```js 
export const supabase_c = createClient(SUPABASE_PROJECT_URL, SUPABASE_KEY, {
  auth: {
    storage: new LargeSecureStore(),
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: false,
  },
});

//Also I tried:
supabase_c.auth.refreshSession().then((res)=>{
            console.log("REFRESH SESSION",res)
        }).catch((error)=>{
            console.log("ERROR REFRESH SESSION",error)
        })
```        
Nothing is working. AutoRefreshToken:true not work, neither refreshSession().

My "solution" right now is set the token to 5 days and logout the user by that time

**Comment by elliott44k** [comment] 2024-02-13 16:39
> This issue still valid for me:
> 
> ```js
> export const supabase_c = createClient(SUPABASE_PROJECT_URL, SUPABASE_KEY, {
>   auth: {
>     storage: new LargeSecureStore(),
>     autoRefreshToken: true,
>     persistSession: true,
>     detectSessionInUrl: false,
>   },
> });
> 
> //Also I tried:
> supabase_c.auth.refreshSession().then((res)=>{
>             console.log("REFRESH SESSION",res)
>         }).catch((error)=>{
>             console.log("ERROR REFRESH SESSION",error)
>         })
> ```
> 
> Nothing is working. AutoRefreshToken:true not work, neither refreshSession().
> 
> My "solution" right now is set the token to 5 days and logout the user by that time

Have you tried using supabase.auth.startAutoRefresh()?
[Docs](https://supabase.com/docs/reference/javascript/auth-startautorefresh)

I'm reading through the docs as I organize tools ahead of the start of my project, and this is something I noticed.
