### ISSUE TITLE
Supabase-js v2 signInWithOtp – invalid refresh_token for idle users if JWT expiries

### ISSUE THREAD

**Issue by garylake** [supabase/gotrue-js#558] opened 2022-11-08 10:07 UTC
# Bug report

## Describe the bug

I have a Vue 3 SPA using Pinia and Vue Router. I use signInWithOtp as my auth method. I recently updated to supabase-js v2 and everything seemed fine at first but I noticed I was always being logged out when accessing the Vue app from a new tab later in the day (I think I've resolved this now). So I suspected the refresh_token might not be working and investigated. 

I lowered my JWT expiry to 360 seconds so I wouldn't have to wait long to test the refresh token. After some tweaks, the refresh_token seems to be working when returning via a new tab in the browser that has the session (even after the JWT should have expired). But I've noticed that when sat there with my app open, if the JWT expires while the app is open, the console starts looping 400 errors and 'Invalid refresh_token'. If I then refresh my app, sometimes it's ok but sometimes supabase.auth.getSession() returns null and my auth guard sends the user to the login page. 

Obviously my JWT will be set back to a longer period once I've got to the bottom of this but I want to make sure there isn't a bug lurking under the surface here. 

## To Reproduce

1. Set a short JWT expiry (a few minutes)
2. signInWithOTP
3. Watch google console at expected time of JWT expiry
4. See 400 and Invalid refresh_token errors

## Expected behavior

JWT should be silently renewed via refresh_token

## Screenshots

As well as the 400 errors, I sometimes get 500 errors and I also sometimes see database deadlock errors but not since I've tried to screen grab it.

In short, everything is fine and then it seems the JWT is expiring in the background and then the refresh_token is failing. If I keep browsing around the app, everything is fine. 

![image](https://user-images.githubusercontent.com/6620087/200528914-b8140b74-0793-4595-9538-69ea3483585e.png)

## System information

- OS: MacOS 12.5.1
- Browser: NA
- Version of supabase-js: 2.0.5
- Version of Node.js: 18.1

## Additional context

My general application flow is:

1. signInWithOtp
```
      const supabaseClient = useCreateSupabaseClient();
      const { error } = await supabaseClient.auth.signInWithOtp({ 
        email: userData.email, 
        options: {
          emailRedirectTo: window.location.origin,
        },
      });
```
2. User follows magic link
3. in `router.beforeEach` I check if requires auth, and if it does I call supabase.auth.getSession(). Otherwise, because of possible race conditions historically from supabase-js v1, or the fact the user could be following a magiclink, I don't assume they aren't logged in, and I redirect to a SessionHelper route/component which onMounted will either deal with the magiclink or will async/await the supabase.auth.getSession() again. Sort of giving the user a second bite at the cherry but I could probably refactor this out since v2. My problem isn't in sessionHelper anyway... 
```
router.beforeEach(async (to, from, next) => {  
  const accountStore = useAccountStore();
  const supabaseClient = useCreateSupabaseClient();
  
  if(to.meta.requiresAuth) {
    const { data: { session } } = await supabaseClient.auth.getSession();
    accountStore.session = session;
    if(accountStore.getSession) {
      next(); // authed carry on...
    }
    else {
      next('/account/session?redirect=' + to.path.replace(/^\/+/, ''));  
    }
  }
```
5. In SessionHelper I basically asycn/await call supabase.getSession(), store it in Pinia and the redirect to where the originally intended to go. As you can see it's not doing much... 
```
    onMounted(async () => {
      if(typeof route.query.redirect !== 'undefined') {
        // preserve any previous redirects...
        redirect = route.query.redirect;
      }

      const { data: { session } } = await supabaseClient.auth.getSession();
      accountStore.session = session;

      if(accountStore.getSession === null) {
        router.push('/account/login?redirect=' + redirect);
      }
      else {
        router.push('/' + redirect);
      }
    });
```
7. If I still don't have a session I kick the user to login screen

To recap, the problem I'm getting is when the user is just sat in the app, idle, doing nothing and the JWT happens to expire while sat doing nothing in the app, then it all starts to fall down with the invalid refresh_token errors.

**Comment by j4w8n** [comment] 2022-12-12 08:07
@garylake is it safe to say that everything works fine as long as someone is using the application?

**Comment by garylake** [comment] 2022-12-12 09:00
@j4w8n Yep, 100% fine as long as token doesn't expire while the browser is open. It's so weird, if the token expires but browser isn't open, and I return, refresh token works. 

But if I leave the browser open and token expires with window open, refresh token is invalid. 

I'm leaning towards this being a me problem purely because I've since implemented the same supabase project with an Ionic/Vue app and it appears fine. (Saying that, if @uze is getting similar then maybe it's not me). 

I will verify this later by dropping my token expiry down again and just double checking the ionic app as well.

**Comment by j4w8n** [comment] 2022-12-12 09:49
Ok. This may have nothing to do with it, but I am curious why your onMounted code sets accountStore.session to session, but the next line checks accountStore.getSession

**Comment by j4w8n** [comment] 2022-12-12 09:50
As you may know, when it throws an invalid refresh token error, it's usually because the token was already used to refresh a session.

**Comment by garylake** [comment] 2022-12-12 10:20
Yeah my implementation was a bit cack handed because with supabase js v1 getting the session wasn't async and I was in race condition hell with vue router. I then updated to supabase js v2 which gave me the async getSession.  

I've since implemented from scratch starting with supabase v2 on my ionic app and it's a lot cleaner, so I think I need to do some testing with short expiries on my ionic app to confirm it's not an issue, and then maybe look at further cleaning up my main Vue app implementation to match and seeing if I can solve this myself. 

For the record, I hadn't started my ionic app when I opened this issue so I had no other working examples. 

Cheers Jason 👍🏻

**Comment by uze** [comment] 2022-12-13 01:28
Just for some context I'm getting the same issue but for react-native. I thought it could be related to this issue: https://github.com/supabase/gotrue-js/issues/495 where the potential issue could be the logic for testing if the current session is inside of the browser but it looks like they've corrected this: https://github.com/supabase/gotrue-js/pull/546. Even after this correction I still see this issue on my end when testing that branch. I currently have my supabase client set up as so:

```
export const createSupabaseClient = () =>
  createClient(supabaseUrl, supabaseAnonKey, {
    auth: {
      autoRefreshToken: true,
      storage: AsyncStorage,
      persistSession: false,
      detectSessionInUrl: false,
    },
  });
  ```

but the autoRefreshToken only seems to work when I leave the app and come back in (similar to this). If I idle in the application the token will eventually expire and I will get: `error: AuthApiError: invalid JWT: unable to parse or verify signature, token is expired by 50s` for every supabase call I make.

cc: @j4w8n @garylake

**Comment by hf** [comment] 2022-12-30 14:45
Hey so recently I've started #564 which should make it simpler to catch this type of issues.

I'd appreciate it if you could send us some code that you are able to reproduce the problem with so we can play around with it.

**Comment by hf** [comment] 2023-08-10 07:49
Is this still happening @garylake?

**Comment by garylake** [comment] 2023-08-15 14:02
@hf yep, just dropped my JWT expiry to 90 seconds and if I just sit on page and do nothing for 90 seconds I start getting 429 errors (no actual message text) on the refresh token. 

`https://<mydomain>/auth/v1/token?grant_type=refresh_token 429`

Happy to share code but it's a fairly large Vue router based app so it's not like I have a single file implementation I can just stick up here.

I'm on a pro plan for the project in question, I'm happy to take this to support or zoom call and work through it, maybe discuss repo access once verified etc?

**Comment by hf** [comment] 2023-12-19 17:55
OK this should be fixed. Don't drop the expiry to values <2 minutes. Here's why: https://supabase.com/docs/guides/auth/sessions#what-are-recommended-values-for-access-token-jwt-expiration

**Closed by hf** 2023-12-19 17:55 UTC
Labels: bug
