### ISSUE TITLE
SMS login OTP not being sent to user upon signup. 

### ISSUE THREAD

**Issue by younusmahmood** [supabase/gotrue-js#133] opened 2021-08-30 16:34 UTC
Hey, I'm working on a react native app using supabase and running into some issues with signing up users. The SMS login OTP is not being sent to the user upon signup, I just get the returned user object, and then I'm authenticated in my app, where I'm expecting to get a text and verify. I double-checked and made sure my number was verified and the only way to get the OTP is to go into supabase users table and send the OTP from there, even though it doesn't do anything for verifying the users account since it's already verified (which is the bug). The SMS auth works perfect for logging in, I send the phone number and I get a text and then verify and I log in so I'm not sure why it doesn't work for signup. 

This is what it says in the docs: 
"A phone number can be used instead of an email as a primary account confirmation mechanism.
**The user will receive a mobile OTP via SMS with which they can verify that they control the phone number.**
You must enter your own Twilio credentials on the auth settings page to enable SMS confirmations." 

I also think it would be nice to allow us to send in the users email along with phone and password while signing up, even for using phone auth. It would be nice to let us still store it even though it's not the primary form of authentication. I tried to just send it in and it didn't store it, I'll open another issue for feature request on this one.

Thanks for any help, loving all the cool stuff you all are building!

**Comment by awalias** [comment] 2021-09-27 11:59
hey @younusmahmood could you share exactly which code you are trying?

and do you have "Enable phone confirmations" enabled in the Auth Settings page?

![image](https://user-images.githubusercontent.com/458736/134903832-f71715ad-55a2-4f27-9a34-29340189367e.png)

**Comment by younusmahmood** [comment] 2021-09-27 19:51
Hi, 

I have the same settings as you for the auth. This is my code:
`   
 const { user, error } = await supabase.auth.signUp({
      phone,
      password,
    });
`
This returns a user but the user never gets the OTP on sign up. To mitigate this (which is the only solution I found to still get the user to input the OTP) was get the user from sign up and then sign the user in. On signIn the OTP is being sent.

**Comment by iamabhishek229313** [comment] 2021-11-11 13:03
> Any update on this? I'm running into another problem with sign-in. The user is never returned
> 
> Here's my code for login (signup code is in my last post):
> 
> ```
> const { user, error } = await supabase.auth.signIn({
>       phone,
> });
> ```
> 
> In this case "user" and "error" both return null.

I'm also getting this error. Did you find any solution?

**Comment by realmichaelye** [comment] 2022-01-17 05:59
Have the same error as well, any solution? @awalias

**Comment by kbanta11** [comment] 2022-04-12 15:12
> running into another problem with sign-in. The user is never returned
> 
> Here's my code for login (signup code is in my last post):

I believe that the user is null until they are confirmed (I'm not sure why, this caused me some issues as well). So even if they successfully are created, you can't get their user ID until they confirm (which really causes problems when doing passwordless sign-in like this, since you can't save any user details in your own table since you don't have a user ID to tie those details too).

Right now I'm having to do a workaround of setting up a database trigger to automatically add half the user details into my own "users" table, and then have to make a call from a backend server (with a service auth key, not anon key) that can search the users table to see if a user exists with a given phone/email, and then create the rest of the user details with the userID from that lookup (has to be done from the backend server to be able to query anything without a user id in the session).

This is pretty clunky and it really would be ideal if the user ID could be returned when the user is created (we know it exists, since it is saved in the Auth users table, its just not exposed).

**Comment by kangmingtay** [comment] 2022-09-28 05:09
Hey everyone, I think there are a few issues being discussed in this thread.

1. The SMS login OTP is not being sent to the user upon signup
@younusmahmood if you are still facing this issue, please reach out to us at [support](https://app.supabase.com/support/new) and we can help to investigate the issue.

2. ... allow us to send in the users email along with phone and password while signing up
This won't be implemented because we treat the phone or email as the primary identifier. If we allow passing both email and phone in signup, then it will require the user to potentially confirm one of them at least. This quickly makes the auth flow even more complex - do we send both a confirmation email and sms otp to the user? 

One alternative is to call the signup method first followed by the update user method to add the user's email / phone number subsequently. Another possible alternative would be to add the user's email / phone number in the `user_metadata` field if you do not require it to be confirmed.

3. The user is never returned. (when calling passwordless signIn methods - either with magiclink or sms otp)
This is something we can consider adding to gotrue! Will add it to our internal backlog. Thanks!

Will be closing this issue since this one has quite a few sub-issues that are not related to the title.

**Closed by kangmingtay** 2022-09-28 05:09 UTC
