### ISSUE TITLE
Concurrent token refreshes can lead to unintentional signing out of users when multiple tabs are open

### ISSUE THREAD

**Issue by bnjmnt4n** [supabase/gotrue-js#213] opened 2022-01-20 06:28 UTC
# Bug report

## Describe the bug

`gotrue-js` uses `localStorage` to store the refresh token. When the user has multiple tabs open, multiple instances of the `GoTrueClient` will be instantiated, with each reading from `localStorage` the same identical access and refresh tokens. There can be cases where both tabs will attempt to refresh using the same token at the same time, which leads to the first request succeeding, but the second request failing due to token reuse detection (https://github.com/supabase/gotrue/pull/226).

## To Reproduce

1. Reduce the JWT expiry from the default 1 hour to 1 minute or lesser.
2. Login into an app using Supabase in a single tab.
3. Open the app in a second tab.
4. Open the network inspector and observe refresh token requests. Eventually both tabs will have failing requests due to reuse of the same refresh token.

## Expected behavior

There is some kind of locking mechanism which avoids concurrent refreshes using the same refresh token. https://github.com/supabase/gotrue-js/pull/203 attempts to do this, but it doesn't account for the multi-tab use case.

## System information

This is likely reproducible on other browsers, but here's the one I tested with:

- OS: Windows
- Browser (if applies): Firefox
- Version of supabase-js: 1.28.6

## Additional context

I will be testing out some changes to `gotrue-js` and will send a PR if it successfully fixes this issue.

**Comment by TheOnlyBeardedBeast** [comment] 2022-02-01 22:37
@bnjmnt4n @inian I think this issue is not frontend related issue, I went deep into the gotrue server implementation, everytime you request a new refresh token, gotrue revokes the old one. As you are in different tabs with shared refresh tokens, the tab which does the refresh first revokes the refresh token for the other tabs, so the other tabs cant get a new access token. Overcoming this issue means that only one tab can make the refresh and it needs to share the access and refresh tokens with the others. Maybe the broadcast chanell api? The second option is to not revoke the refresh token, but that would blow the security.

From the GoTrue server source code, clearly visible that it revokes the old token.
```golang
// GrantRefreshTokenSwap swaps a refresh token for a new one, revoking the provided token.
func GrantRefreshTokenSwap(tx *storage.Connection, user *User, token *RefreshToken) (*RefreshToken, error) {
	var newToken *RefreshToken
	err := tx.Transaction(func(rtx *storage.Connection) error {
		var terr error
		if terr = NewAuditLogEntry(tx, user.InstanceID, user, TokenRevokedAction, nil); terr != nil {
			return errors.Wrap(terr, "error creating audit log entry")
		}

		token.Revoked = true
		if terr = tx.UpdateOnly(token, "revoked"); terr != nil {
			return terr
		}
		newToken, terr = createRefreshToken(rtx, user)
		return terr
	})
	return newToken, err
}
```

But if I missread somehow the go source code, please let me know.

**Comment by bnjmnt4n** [comment] 2022-02-02 08:49
@TheOnlyBeardedBeast The gotrue behaviour is correct; this is more of an issue with the gotrue-js implementation.

> As you are in different tabs with shared refresh tokens, the tab which does the refresh first revokes the refresh token for the other tabs, so the other tabs cant get a new access token. Overcoming this issue means that only one tab can make the refresh and it needs to share the access and refresh tokens with the others.

This is exactly the gist of the problem. Both tabs do not notify each other that they are attempting a refresh, so it is possible for 2 parallel refresh attempts to occur at nearly the same time. One of them will likely succeed first, returning a new refresh token. However, the other refresh attempt will cause the new refresh token to be revoked due to the use of the same original refresh token.

I think there are possibly 2 paths to take:
1. If the same refresh token is used multiple times within a given period, do not revoke any descendant refresh tokens. This solution is brittle since network latency differs across users and regions, and potentially replay attacks could be used to generate/obtain new refresh tokens.
2. Implement a locking solution on the client-side to ensure that refreshes across multiple tabs will never use the same refresh token. I have some naive code which attempts to do locking via `localStorage`, but it is a bit of a mess, and I'll try to clean it up before potentially making a PR. (I need to double-check the integration with `supabase-js` as well.) [`BroadcastChannel`](https://developer.mozilla.org/en-US/docs/Web/API/BroadcastChannel#browser_compatibility) or the web locking API isn't supported in Safari, so I didn't look into that. Perhaps the [Web locking APIs](https://developer.mozilla.org/en-US/docs/Web/API/Web_Locks_API#browser_compatibility) could be used in the future as well.

**Comment by TheOnlyBeardedBeast** [comment] 2022-02-02 09:19
@bnjmnt4n thanks for the reply, I am working on client myself handling the same issue (not gotrue-js, but the api was based on gotrue and behaves the same), currently what I am doing is listening to storage events and updating the clients refresh token memory representation in different tabs. It works well but I think in the future I can  encounter similar issues as you when a new tab is opened on the edge of the refresh interval of the current tab so a refresh starts while a different refresh is in progress. Perhaps a simple onetime retry after the first failed refresh happens could also help, that failed refresh would mean that a new refresh token should already exist in the storage. But your idea with a locking mechanism sounds good. You could wrap a storage change event into a promise, checking for a specific key, before the refresh request you can await that given promise which resolves when the given key does not exist in the storage, or its value means that a refresh is not pending in a different tab. 

I will definitely try something out, thanks for the brainstorming.

**Comment by liaujianjie** [comment] 2022-03-09 06:09
IMO this race condition can be resolved with leader election. That is, we select a single tab, using a leader election algorithm, to perform the token refresh when it is time to perform a refresh. There's a [`tab-election`](https://github.com/dabblewriter/tab-election) package that we can take reference from.

Alternatively, a temporary cheap solution would be to randomize the [time at which the token refreshes](https://github.com/supabase/gotrue-js/blob/f80da9d0be2d610295ee7bd1f7fbd8e9d5f5ea96/src/GoTrueClient.ts#L702). Though an incomplete solution, this would significantly reduce the likelihood of a clash.

**Comment by thorwebdev** [comment] 2022-05-04 03:38
This is now being worked on server-side in gotrue: https://github.com/supabase/gotrue/pull/466

**Comment by thorwebdev** [comment] 2022-05-17 05:59
@chipilov I'm not able to reproduce this anymore. Can you provide some screenshots of your network tabs? For me it is now correctly working and replaying the request (see screenshots). Do note that the default reuse interval is 10s. So if the requests are further apart than that the tokens will be revoked. 

<img width="719" alt="image" src="https://user-images.githubusercontent.com/5748289/168739371-9b14a635-edaa-4edd-a9e1-5c3666bc8b6d.png">
<img width="719" alt="image" src="https://user-images.githubusercontent.com/5748289/168739453-7e2ecf6e-4936-4967-879e-8168fa630f71.png">

**Closed by thorwebdev** 2022-05-17 05:59 UTC
Labels: bug

**Comment by chipilov** [comment] 2022-05-17 06:59
Hi @thorwebdev,

I am attaching a screenshot of the issue:

![token_requests](https://user-images.githubusercontent.com/389130/168748113-4796f83d-07d6-421f-a926-adcb0a68e797.jpg)

Some additional info:
  - supabase-js is at 1.22.15;
  - GoTrue server for the project as reported by the /health API is at v2.6.30
  - I am using a pretty frequent refresh interval (30seconds) just to make it easier to repro
  - you can probably see from the timestamps of the requests but they are almost simultaneous so they definitely fall within the 10s interval

Finally, I am not sure what you mean by "replaying the requests". My impression was that the fix was entirely on the server side so that if 2 token refresh requests for the same token arrive at the server within 10s from each other both of them will receive 200 responses with the new token. Is that not the case (i.e. is there an additional retry handling in the client)?

Let me know if you need more info.

**Comment by kangmingtay** [comment] 2022-05-17 14:10
Hey @chipilov, 

>  I am not sure what you mean by "replaying the requests"
Yes, if the reuse interval is set to 10s, then the client has a leeway time of 10 seconds to make the refresh using the same token. Gotrue will simply return the latest valid child token instead of generated a new one. 

For example:

```
token | parent 
foo       -
bar       foo
```

1. First request to refresh using token `foo` returns token `bar`. Reuse interval starts here.
2. As long as `foo` is still within the reuse interval, you can make as many requests to refresh as you like and gotrue will always return `bar`.
3. A token can be reused as long as it satisfies both of these conditions:

a. Token is used within reuse interval
b. Token must be the last revoked token

For example: 

```
token | parent | revoked
foo       -        t
bar       foo      t
baz       bar      f 
```

If a refresh request is made using `bar` to get `baz`, then trying to use `foo` to refresh again will trigger the automatic reuse detection and invalidate all it's descending tokens. This is because `foo` is now the second-last revoked token.

**Comment by chipilov** [comment] 2022-05-17 18:44
Just to close the loop on my particular issue: @kangmingtay identified the problem (a newly introduced env var was not loaded in my project for some reason) and fixed it - thanks!

So the server-side fix seems to work as long as the new env vars are properly loaded into a project.

**Comment by cinan** [comment] 2022-11-04 14:13
I can still reproduce this bug with local supabase instance. Supabase-cli: `1.11.4`, supabase-js: `2.0.4`.  It looks like `gotrue` server (`2.15.3`) wasn't configured with `GOTRUE_SECURITY_REFRESH_TOKEN_REUSE_INTERVAL` variable. If I call two simultaneous refresh tokens requests, one of them always fails due to invalid refresh token.

**Comment by kangmingtay** [comment] 2022-11-04 16:19
@cinan how are you running the local supabase instance? is it with the docker-compose found [here](https://github.com/supabase/supabase/blob/master/docker/docker-compose.yml#L46)? if you are, then yeah we didn't add the necessary env vars to allow for that yet

**Comment by cinan** [comment] 2022-11-04 16:25
I run `supabase start`which probably uses the docker-compose file you referenced. In `docker inspect` I can see there's no `GOTRUE_SECURITY_REFRESH_TOKEN_REUSE_INTERVAL` variable.
