### ISSUE TITLE
`supabase.auth.getUserByCookie` no longer there in 2.0

### ISSUE THREAD

**Issue by jonluca** [supabase/gotrue-js#492] opened 2022-10-11 15:26 UTC
After upgrading to 2.0, the server side function of getting a user from their cookie or by jwt is no longer there.

Our auth middleware (on a custom Node server, not on Nextjs) looks like this

```ts
const authHeader = req.get("Authorization") || req.get("authorization") || "";
  const cookies = req.cookies;
  if (!authHeader && !cookies) {
    const customError = new CustomError(400, "General", "Authorization not provided");
    return next(customError);
  }

  const token = authHeader.replace("Bearer ", "").trim();

  const checkUser = (user: User | null) => {
    if (!user) {
      const customError = new CustomError(401, "Raw", "No user in auth check", null);
      return next(customError);
    }
    req.supabaseUser = user;
    tracer.setUser({ id: user.id, auth_provider_id: user.id, email: user.email });
    return next();
  };

  try {
    if (token) {
      const { user, error } = await supabase.auth.api.getUser(token);
      if (error) {
        console.error(error);
        if (!cookies) {
          const customError = new CustomError(401, "Raw", "JWT error from supabase", null, error);
          return next(customError);
        }
      } else {
        return checkUser(user);
      }
    }

    if (cookies) {
      const { user, error } = await supabase.auth.getUserByCookie(req, res);
      if (error) {
        console.error(error);
        const customError = new CustomError(401, "Raw", "Cookie error", null, error);
        return next(customError);
      }
      return checkUser(user);
    }

    // in the case neither auth headers or a cookie was sent
    const customError = new CustomError(401, "Raw", "No valid authentication methods found!", null);
    return next(customError);
  } catch (err) {
    console.error(err);
    const customError = new CustomError(401, "Raw", "JWT error", null, err);
    return next(customError);
  }
```

**Comment by LukasMurdock** [comment] 2022-10-24 09:12
@jonluca Came across this same issue when upgrading to 2.0.

Seems the removal of all cookie related methods is a feature not a bug in v2: https://github.com/supabase/gotrue-js/commit/6211cf13a93b088eccc894c6c8d0410eb42d2db4

Supabase guide for [Server-Side Rendering](https://supabase.com/docs/guides/auth/server-side-rendering) seems to have been added a few days ago and provides this example of setting your own cookies for `access_token` and `refresh_token` on the client:

```ts
supabase.auth.onAuthStateChange((event, session) => {
  if (event === "SIGNED_OUT" || event === "USER_DELETED") {
    // delete cookies on sign out
    const expires = new Date(0).toUTCString();
    document.cookie = `my-access-token=; path=/; expires=${expires}; SameSite=Lax; secure`;
    document.cookie = `my-refresh-token=; path=/; expires=${expires}; SameSite=Lax; secure`;
  } else if (event === "SIGNED_IN" || event === "TOKEN_REFRESHED") {
    const maxAge = 100 * 365 * 24 * 60 * 60; // 100 years, never expires
    document.cookie = `my-access-token=${session.access_token}; path=/; max-age=${maxAge}; SameSite=Lax; secure`;
    document.cookie = `my-refresh-token=${session.refresh_token}; path=/; max-age=${maxAge}; SameSite=Lax; secure`;
  }
})
```

Presumably, then on the server you could parse the cookie and pass in the `access_token` jwt to [getUser](https://supabase.com/docs/reference/javascript/auth-getuser)

**Comment by kangmingtay** [comment] 2022-10-26 13:46
Gonna close this issue since @LukasMurdock is right!

**Closed by kangmingtay** 2022-10-26 13:46 UTC
Labels: bug
