### ISSUE TITLE
signOut does not clear user jwt from gotrue authorization header allowing gotrue operations and exposing user jwt

### ISSUE THREAD

**Issue by GaryAustin1** [supabase/gotrue-js#524] opened 2022-10-29 17:14 UTC
# Bug report

## Describe the bug
This is from a user discussion on [DISCORD](https://discord.com/channels/839993398554656828/1035578821853855815 )

Although signOut clears the session data from local storage, it appears it leaves the user jwt in the gotrue headers object and in a second object called changedAccessToken.

If you run getUser() after signOut a request to the server goes out and the user data is returned. 
Although database API calls revert to the anon key, the jwt could also be copied and used until it expires.

A temporary solution is probably to set the client "object" to null, or reinitialize the client if further work needs to be done after signout.

## To Reproduce
```
console.log('login')
        const {data} = await supabase1.auth.signInWithPassword({email: 'email', password:'pass'} )
        console.log('login ',data)
        console.log('signOut ',await supabase1.auth.signOut())
        console.log('getSession ', await supabase1.auth.getSession())   //null
        console.log('supabase ',supabase1)  //see image below
        const result = await supabase1.from('realtest').select()  //authentication header anon
        console.log ('getUser ', await supabase1.auth.getUser())  //auth header has user jwt and returns user data from server
```
Supabase object after signOut()
![signout](https://user-images.githubusercontent.com/54564956/198843903-9c1a2ba5-205d-49bc-b220-86f5e1d6c8ce.JPG)

getUser going out with a user jwt after signOut().
![image](https://user-images.githubusercontent.com/54564956/198844032-df4efafc-c0ff-4060-9dad-795faf89bc07.png)

## Expected behavior

SignOut() should remove any jwt info from memory and certainly no allow gotrue operations to continue.   

It is understood there is a risk of unexpired jwts after signOut, but they should not be left around for someone to find or use after signOut().

## System information

supabase-js 2.0.4

**Comment by GaryAustin1** [comment] 2022-11-04 00:25
This is a slightly different issue, but related to auth having its own headers...

.getUser(jwt) if called while using service_role sets the authentication header in auth to the User JWT.
The supabase client header still stays service_role, but if you make further admin auth calls after doing a .getUser call they will be rejected with 401.

If this is desired behavior (getUser(jwt) then this should be documented as users are running into this server side.

![getUser](https://user-images.githubusercontent.com/54564956/199859400-7a18244d-52e3-445f-af16-b1aeceaa2a26.JPG)

**Comment by j4w8n** [comment] 2022-11-06 18:01
I was able to reproduce this. Resolved by adding the following to `dist/main/SupabaseClient.js` in the @supabase/supabase-js codebase. This would be `src/SupabaseClient.ts` [here](https://github.com/supabase/supabase-js/blob/master/src/SupabaseClient.ts#L281-L300). I believe this is the correct spot to make these changes; but I honestly don't know, as I struggled to figure out how headers get set (possibly in a function passed to `fetch` [here](https://github.com/supabase/supabase-js/blob/master/src/SupabaseClient.ts#L122), because `_getAccessToken()` seems to call `getSession()` and the return the access token for `fetch`'s use)

```diff
  _handleTokenChanged(event, token, source) {
    if ((event === 'TOKEN_REFRESHED' || event === 'SIGNED_IN') &&
      this.changedAccessToken !== token) {
      // Token has changed
      this.realtime.setAuth(token ?? null);
      this.changedAccessToken = token;
    } 
    else if (event === 'SIGNED_OUT' || event === 'USER_DELETED') {
      // Token is removed
      
      this.realtime.setAuth(this.supabaseKey);
+     this.changedAccessToken = undefined;
+     this.auth.headers.Authorization = `Bearer ${this.supabaseKey}`;
      if (source == 'STORAGE') 
          this.auth.signOut();
    }
  }
}
```

**Comment by j4w8n** [comment] 2022-11-07 13:37
> This is a slightly different issue, but related to auth having its own headers...
> 
> .getUser(jwt) if called while using service_role sets the authentication header in auth to the User JWT. The supabase client header still stays service_role, but if you make further admin auth calls after doing a .getUser call they will be rejected with 401.
> 
> If this is desired behavior for getUser(jwt), then this should be documented as users are running into this server side.
> 
> This image is of auth's headers in the supabase "object".
> 
> ![getUser](https://user-images.githubusercontent.com/54564956/199859400-7a18244d-52e3-445f-af16-b1aeceaa2a26.JPG)

I went ahead and created issue https://github.com/supabase/gotrue-js/issues/531 for this.

**Comment by thorwebdev** [comment] 2022-11-21 08:12
I think the root cause of this might be https://github.com/supabase/supabase/issues/5990

**Comment by hf** [comment] 2022-12-30 15:36
Added a PR for the suggested change by @j4w8n. Will close this issue.

**Closed by hf** 2022-12-30 15:36 UTC
Labels: bug
